// Country name to ISO 3166-1 alpha-2 for UPS API (worldwide + Canada)
export const countryCodeMap = {
  "United States": "US",
  "United States of America": "US",
  USA: "US",
  Canada: "CA",
  "United Kingdom": "GB",
  "Great Britain": "GB",
  UK: "GB",
  "Puerto Rico": "PR",
  "Virgin Islands": "VI",
  "Virgin Islands, U.S.": "VI",
  Guam: "GU",
  "American Samoa": "AS",
  "Northern Mariana Islands": "MP",
  Mexico: "MX",
  Australia: "AU",
  Austria: "AT",
  Belgium: "BE",
  Brazil: "BR",
  China: "CN",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  Denmark: "DK",
  Finland: "FI",
  France: "FR",
  Germany: "DE",
  "Hong Kong": "HK",
  "Hong Kong SAR": "HK",
  India: "IN",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Japan: "JP",
  Malaysia: "MY",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Norway: "NO",
  Poland: "PL",
  Portugal: "PT",
  Singapore: "SG",
  "South Korea": "KR",
  "Korea, Republic of": "KR",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  "United Arab Emirates": "AE",
  UAE: "AE",
  Vietnam: "VN",
  // Worldwide additions
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Angola: "AO",
  Argentina: "AR",
  Armenia: "AM",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bolivia: "BO",
  "Bosnia and Herzegovina": "BA",
  Botswana: "BW",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Cambodia: "KH",
  Cameroon: "CM",
  "Cape Verde": "CV",
  "Cayman Islands": "KY",
  Chile: "CL",
  Colombia: "CO",
  "Costa Rica": "CR",
  "Côte d'Ivoire": "CI",
  "Ivory Coast": "CI",
  Croatia: "HR",
  Cyprus: "CY",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  Estonia: "EE",
  Ethiopia: "ET",
  Fiji: "FJ",
  Gabon: "GA",
  Georgia: "GE",
  Ghana: "GH",
  Greece: "GR",
  Guatemala: "GT",
  Guyana: "GY",
  Honduras: "HN",
  Hungary: "HU",
  Iceland: "IS",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Jamaica: "JM",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Latvia: "LV",
  Lebanon: "LB",
  Libya: "LY",
  Lithuania: "LT",
  Luxembourg: "LU",
  "North Macedonia": "MK",
  Macedonia: "MK",
  Madagascar: "MG",
  Malta: "MT",
  Mauritius: "MU",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Morocco: "MA",
  Mozambique: "MZ",
  Namibia: "NA",
  Nepal: "NP",
  Nicaragua: "NI",
  Nigeria: "NG",
  Oman: "OM",
  Pakistan: "PK",
  Panama: "PA",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Qatar: "QA",
  Romania: "RO",
  Russia: "RU",
  "Russian Federation": "RU",
  Rwanda: "RW",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Slovakia: "SK",
  Slovenia: "SI",
  "South Africa": "ZA",
  "Sri Lanka": "LK",
  Taiwan: "TW",
  Tanzania: "TZ",
  Thailand: "TH",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  Türkiye: "TR",
  Uganda: "UG",
  Ukraine: "UA",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Venezuela: "VE",
  "West Bank and Gaza": "PS",
  Palestine: "PS",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};

// Get country code from country name or 2-letter code (case-insensitive)
export function getCountryCode(countryName) {
  if (!countryName || typeof countryName !== "string") return "US";
  const s = countryName.trim();
  if (s.length === 2 && /^[A-Za-z]{2}$/.test(s)) {
    return s.toUpperCase();
  }
  return countryCodeMap[s] || countryCodeMap[s.replace(/\s+/g, " ")] || "US";
}

// Countries for dropdown (worldwide, US and Canada first)
export const countries = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Mexico",
  "Germany",
  "France",
  "Japan",
  "Italy",
  "Spain",
  "Netherlands",
  "Brazil",
  "China",
  "India",
  "South Korea",
  "Ireland",
  "Sweden",
  "Belgium",
  "Austria",
  "Switzerland",
  "Israel",
  "New Zealand",
  "Singapore",
  "Portugal",
  "Norway",
  "Poland",
  "Denmark",
  "Finland",
  "Czech Republic",
  "United Arab Emirates",
  "Malaysia",
  "South Africa",
  "Argentina",
  "Chile",
  "Colombia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Hungary",
  "Romania",
  "Greece",
  "Hong Kong SAR",
  "Egypt",
  "Saudi Arabia",
  "Indonesia",
  "Pakistan",
  "Bangladesh",
  "Nigeria",
  "Kenya",
  "Belize",
  "Costa Rica",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Guatemala",
  "Honduras",
  "Jamaica",
  "Nicaragua",
  "Panama",
  "Peru",
  "Trinidad and Tobago",
  "Uruguay",
  "Venezuela",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Armenia",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Barbados",
  "Belarus",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bulgaria",
  "Burkina Faso",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Côte d'Ivoire",
  "Croatia",
  "Cyprus",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Gabon",
  "Georgia",
  "Ghana",
  "Iceland",
  "Iran",
  "Iraq",
  "Jordan",
  "Kazakhstan",
  "Kuwait",
  "Kyrgyzstan",
  "Latvia",
  "Lebanon",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "North Macedonia",
  "Madagascar",
  "Malta",
  "Mauritius",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Oman",
  "Paraguay",
  "Qatar",
  "Russia",
  "Rwanda",
  "Senegal",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Sri Lanka",
  "Taiwan",
  "Tanzania",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "Uzbekistan",
  "Zambia",
  "Zimbabwe",
  "American Samoa",
  "Bermuda",
  "Guam",
  "Northern Mariana Islands",
  "Puerto Rico",
  "Virgin Islands",
  "West Bank and Gaza",
];

// Canadian provinces/territories (code, name) for address forms
export const canadianProvinces = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
];
